apiVersion: v2
name: github-deploy-key-operator
description: A Kubernetes operator that manages GitHub deploy keys
type: application
version: 0.1.0
appVersion: "latest"
maintainers:
  - name: gurghet
keywords:
  - github
  - deploy-key
  - operator
  - flux
annotations:
  "com.github.fluxcd.source-controller/flux-patch-allowed": "true"
  "com.github.fluxcd.source-controller/ignore": "false"
  "com.github.fluxcd.source-controller/source-checksum": "true"
  "com.github.fluxcd.source-controller/source-controller-gen": "true"
  "com.github.fluxcd.source-controller/source-controller-gen-version": "v1beta2"
  "com.github.fluxcd.source-controller/source-controller-gen-api-version": "source.toolkit.fluxcd.io/v1beta2"
  "com.github.fluxcd.source-controller/source-controller-gen-experimental": "true"
  "com.github.fluxcd.source-controller/source-controller-gen-experimental-api-version": "source.toolkit.fluxcd.io/v1beta2"
  "com.github.fluxcd.source-controller/source-controller-gen-version": "v1beta2"
  includesCRDs: "true"
