# Default values for github-deploy-key-operator.

replicaCount: 1

image:
  repository: ghcr.io/gurghet/github-deploy-key-operator/operator
  tag: latest  # We recommend using a specific version
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

# GitHub configuration
github:
  # -- GitHub token (not recommended, use existingSecret instead)
  token: ""
  
  # -- Name of existing secret containing the GitHub token
  existingSecret: ""
  
  # -- Key in the existing secret that contains the GitHub token
  existingSecretKey: "GITHUB_TOKEN"

# Security context configuration
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL

# Service account configuration
serviceAccount:
  # -- Create a service account
  create: true
  # -- Service account name (if not creating one)
  name: ""
  # -- Annotations to add to the service account
  annotations: {}

# Resource limits
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}
