# Default values for github-deploy-key-operator.

# -- Number of operator replicas to run
replicaCount: 1

# -- Container image configuration
image:
  # -- Image repository in format: ghcr.io/gurghet/github-deploy-key-operator/operator
  repository: ghcr.io/gurghet/github-deploy-key-operator/operator
  # -- Image tag (we recommend using a specific version instead of latest)
  tag: latest
  # -- Image pull policy
  pullPolicy: Always

# -- Override the chart name
nameOverride: ""
# -- Override the full chart name
fullnameOverride: ""

# -- GitHub configuration
github:
  # -- GitHub token (not recommended, use existingSecret instead)
  # This token needs repo or admin:public_key permissions
  token: ""
  
  # -- Name of existing secret containing the GitHub token
  # The secret must be in the same namespace as the operator
  existingSecret: ""
  
  # -- Key in the existing secret that contains the GitHub token
  # Default matches the example in the README
  existingSecretKey: "GITHUB_TOKEN"

# -- Pod security context configuration
# These settings ensure the operator runs with minimal privileges
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault

# -- Container security context
# These settings restrict the operator's capabilities
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL

# -- Service account configuration
serviceAccount:
  # -- Whether to create a service account
  create: true
  # -- Name of the service account to use
  # If not set and create is true, a name is generated
  name: ""
  # -- Annotations to add to the service account
  annotations: {}

# -- Resource limits and requests
# The operator is lightweight but needs enough resources
# to handle multiple repositories
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

# -- Node selector for the operator pod
nodeSelector: {}

# -- Pod tolerations
tolerations: []

# -- Pod affinity rules
affinity: {}
