apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-deploy-key-operator
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-deploy-key-operator
rules:
- apiGroups: ["github.com"]
  resources: ["githubdeploykeys", "githubdeploykeys/status", "githubdeploykeys/finalizers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets", "events", "configmaps", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-deploy-key-operator
subjects:
- kind: ServiceAccount
  name: github-deploy-key-operator
  namespace: flux-system
roleRef:
  kind: ClusterRole
  name: github-deploy-key-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-deploy-key-operator
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-deploy-key-operator
  template:
    metadata:
      labels:
        app: github-deploy-key-operator
    spec:
      serviceAccountName: github-deploy-key-operator
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: operator
        image: ghcr.io/gurghet/github-deploy-key-operator:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: ghcr-secret
              key: github-token
        - name: KOPF_NAMESPACE
          value: ""  # Empty string means watch all namespaces
