apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "github-deploy-key-operator.fullname" . }}
  labels:
    {{- include "github-deploy-key-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "github-deploy-key-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "github-deploy-key-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "github-deploy-key-operator.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  {{- if .Values.github.existingSecret }}
                  name: {{ .Values.github.existingSecret }}
                  {{- else }}
                  name: {{ include "github-deploy-key-operator.fullname" . }}-github
                  {{- end }}
                  key: {{ .Values.github.existingSecretKey }}
            - name: KOPF_NAMESPACE
              value: ""
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
