{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "github-deploy-key-operator.serviceAccountName" . }}
  labels:
    {{- include "github-deploy-key-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "github-deploy-key-operator.fullname" . }}
  labels:
    {{- include "github-deploy-key-operator.labels" . | nindent 4 }}
rules:
- apiGroups: ["github.com"]
  resources: ["githubdeploykeys", "githubdeploykeys/status", "githubdeploykeys/finalizers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets", "events", "configmaps", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "github-deploy-key-operator.fullname" . }}
  labels:
    {{- include "github-deploy-key-operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "github-deploy-key-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "github-deploy-key-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
