{{- if and (not .Values.github.existingSecret) .Values.github.token -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-deploy-key-operator.fullname" . }}-github
  labels:
    {{- include "github-deploy-key-operator.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.github.existingSecretKey }}: {{ .Values.github.token | b64enc }}
{{- end }}
