name: Test GHCR Push

on:
  workflow_dispatch:  # Manual trigger

permissions:
  contents: read
  packages: write

jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push test image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: test.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/test:latest
